version: '3.3'

volumes:
  pg_data:  
  static:  
  media: 

services:
  db:
    container_name: db
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - foodgram_network

  backend:
    ports:
      - "1337:8000"
    container_name: foodgram-back
    image: katerishna/foodgram-backend
    env_file: ../.env
    volumes:
      - type: bind
        source: ../backend/static_backend
        target: /static_backend
      - type: bind
        source: ../backend/media
        target: /app/media
    depends_on:
      - db
    networks:
      - foodgram_network

  frontend:
    container_name: foodgram-front
    image: katerishna/foodgram-frontend
    volumes:
      - ../frontend/:/app/result_build/
    networks:
      - foodgram_network
 
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs:/usr/share/nginx/html/api/docs
      - type: bind
        source: ../backend/media
        target: /app/media
      - type: bind
        source: ../backend/static_backend
        target: /static_backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - foodgram_network

networks:
  foodgram_network:
    driver: bridge