# Generated by Django 4.2.23 on 2025-06-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
