# Generated by Django 4.2.23 on 2025-08-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='unique_user_author',
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_user_author', violation_error_message='Вы уже подписаны на этого пользователя'),
        ),
    ]
