# Generated by Django 4.2.23 on 2025-07-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_subscribed',
        ),
    ]
