# Generated by Django 4.2.23 on 2025-07-12 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_myuser_is_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='following',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='subscriptions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subscriptions',
            unique_together={('user', 'author')},
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='follower',
        ),
    ]
