# Generated by Django 4.2.23 on 2025-07-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_following_subscriptions_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
